[auth]
authenticator_type = "local"
enable_auth_user = true
enable_auth_token = true
enable_auth_endpoint = true
enable_entity_verification = true
enable_verify_tls = false
enable_logging = false
enable_log_entity_verification = false
enable_log_requests = false
enable_log_results = false

[auth.local]
default_userid = 5
default_username = "default_user"

[auth.remote]
url = "https://backend.application.daas-design.de"
clientid = "test-client"
scope = "admin"
username = "johannes.bouche@fb2.fra-uas.de"
password = "Design.2024"
