[filestore]
folder_tmp = "data/tmp"
folder_shared = "data/shared"
folder_upload = "data/upload"
folder_docker = "data/docker"
folder_inst_env = "env"
folder_inst_status = "status"
folder_endpoint_info = "/home/design-daas/backend/web/data/endpoint_info"
instance_status_outfile_name = "cmdout.txt"
instance_status_pidfile_name = "pid.txt"
default_wine_image_folder = "/home/design-daas/backend/installer/wine"
default_wine_image_name = "wine"
default_x11vnc_image_folder = "/home/design-daas/backend/installer/x11vnc"
default_x11vnc_image_name = "x11vnc"
