[log]
enabled = true
log_level = "INFO"
log_dir = "logs"
log_prefix = "%(asctime)s-%(levelname)1.1s-%(name)-9.9s :"
log_message = "%(message)s"
log_details = ""
# logdate = "%Y-%m-%d %H:%M:%S"
log_date = "%H:%M:%S"
log_encode = "utf-8"
console_target = "console"
debug_target = "debug"
error_target = "error"

all_sublogs = false
no_sublogs = false
log_web_enabled = true
log_web_resize = false
log_web_tunnel = false
log_web_client = true
log_web_switcher = false
log_web_watcher = true
log_web_summary = true

log_hypercorn = false
log_debug = true
log_error = true
log_auth = true
log_any = true
log_db = true
log_vm = true
log_sys = true
log_node = true
log_qweb = true
log_runtime = true
log_proc = true
log_layers = true
log_plugin = true
log_proxy = true
log_websocket = true
log_inst = true
log_tasks = true
log_limits = true
log_backend = true
log_frontend = true
log_files_local = true
log_files_ceph = true
log_objects = true
log_automation = true
log_adapter_qmsg = true
log_adapter_ssh = true
log_adapter_http = true
log_console = true
log_console_exclude = [
  # "any",
  # "task",
  # "inst",
  "db",
  # "qmsg",
  # "limit",
  # "auth",
  # "websocket",
]
