[instances]
sshuser = "root"
sshport = 22
sshopt_timeout = 1
sshopt_strictcheck = "no"
sshopt_nohostauth = "yes"
prefixip = "192.168.223"
proxyfile = "daas/env/CommandProxy.py"
logcmd = true
logresult = false
enable_message_queue = true
test_method_online_state = "queue"

[inst_queue]
rabbitmq_host = "172.17.0.1"
host_timeout = 2
cleanup_time = 2
reconnect_time_client = 1
reconnect_time_server = 1
wait_time_ms = 1000
wait_time_total_ms = 300000
log_heartbeats = true
log_topic = "qmsg"


[inst_ssh]
sshuser = "root"
sshhost = "localhost"
sshopt_timeout = 1
sshopt_strictcheck = "no"
sshopt_nohostauth = "yes"
sshport = 22
logcmd = false
logresult = false
