[viewer]
guacd = "127.0.0.1:4822"
viewer_protocol = "https"
viewer_host = "pve1.cluster.local"
viewer_port = 443
token_length = 32
fetch_ms = 3000
check_ms = 1000
observer_ms = 250
reconnect_min_ms = 250
reconnect_default_ms = 1000
reconnect_delayed_ms = 10000
reconnect_max = 10
reconnect_enabled = 1
