[vm_rest]
apiuser = "root@pam"
apipass = "root"
apiurl = "https://127.0.0.1:8006/api2/json"
sessionurl = "access/ticket"
session_lifetime = 3600

[vm_http]
logging = true
verify_tls = false
logrequests = true
logresults = false

[vm_api]
node = "pve1"
hostIp = "192.168.123.111"
prefixip = "192.168.223"
main_folder = "/home"
storage_iso = "daas-iso"
storage_img = "daas-img"
storage_ceph = "daas-ceph"
bridge_name_daas = "vmbr0"
bridge_cidr_daas = "192.168.123.111/24"
bridge_gw_daas = "192.168.123.1"
bridge_adapter_daas = "enp0s4"
bridge_name_inst = "vmbr1"
bridge_cidr_inst = "192.168.223.111/24"
bridge_adapter_inst = ""
bridge_name_ceph = "vmbr8"
bridge_cidr_ceph = "192.168.100.111/24"
bridge_adapter_ceph = ""
bridge_name_cluster = "vmbr9"
bridge_cidr_cluster = "192.168.200.111/24"
bridge_adapter_cluster = ""
prefixmac = "de:ad:be:ef:00"
