from enum import Enum


class PhasesSystemTask(Enum):
    """VM system tasktype"""

    PHASES_POSTBOOT_ACTIONS = "PHASES_POSTBOOT_ACTIONS"
    PHASES_WAIT_FOR_INSTANCE = "PHASES_WAIT_FOR_BOOT"
    PHASES_CREATE_FROM_APP = "PHASES_CREATE_FROM_APP"
    PHASES_CLONE_FROM_APP = "PHASES_CLONE_FROM_APP"
    PHASES_CONFIGURE_CONNECTION = "PHASES_CONFIGURE_CONNECTION"
